# Procesamiento de datasets con Numpy

## Ecommerce Wish 

Para la siguiente práctica, se tomó parte del dataset de las <a href='https://www.kaggle.com/jmmvutu/summer-products-and-sales-in-ecommerce-wish'>ventas de productos de verano de E-commerce Wish</a> que aparece en <a href='https://www.kaggle.com/'>Kaggle</a>.

In [54]:
import numpy as np

In [55]:
nombres = np.loadtxt('datos/summer_products/nombres.csv',encoding='utf-8', dtype='str', delimiter='\n')
nombres.shape

(62,)

In [56]:
# Nombre de los 5 primeros productos
nombres[:5]

array(["5 Color Women's Fashion Summer Slim Sleeveless Camouflage Print Dress High Waist Lace Up Casual Pocket Mini Dresses Plus Size S-5XL",
       'Sexy Solid Ruffled Chiffon Sling Top Pure Color Women Summer Tank Top Plus Size',
       'Women Fashion Short Jumpsuit Spaghetti Strap Sleeveless Rompers Summer One Piece Set Casual Summer Outfits',
       '2018 New Fashion Women Casual Playsuit Ladies Jumpsuit Romper Summer Floral Playsuit Brand New (3 Colors)',
       'Summer Fashion Women Round Neck Sleeveless Pure Color Casual Pocket Dress'],
      dtype='<U181')

In [57]:
etiquetas = np.loadtxt('datos/summer_products/etiquetas.csv',encoding='utf-8', dtype='str', delimiter='\n')
etiquetas.shape

(62,)

In [58]:
# Etiquetas de los 5 primeros productos 
etiquetas[:5]

array(['"Summer,Plus Size,Lace,Mini,Dress,slim,camouflage,Mini dress,Pocket,high waist,Women\'s Fashion,Fashion,Lace Up,t,print dress,Print,sleeveless,bodycon,Casual,Women Fashion,Waist"',
       '"Summer,Plus Size,ruffle,ruffled,chiffon,Tank,Pure Color,Cami,tank top,Women\'s Fashion,Fashion,V-neck,blousesampshirt,sexy,Tops,Women"',
       '"Summer,Shorts,Women,shortromper,Spaghetti,onepiece,Spaghetti Strap,One-Piece Suits,shortjumpsuit,Women\'s Fashion,Fashion,Casual,summerjumpsuit,sleeveless,Rompers,women Jumpsuit,playsuit,jumpsuit"',
       '"Summer,Shorts,Rompers,Casual,Ladies,Women\'s Fashion,Fashion,off shoulder,sexy,Floral,sleeveless,Women,Beach,playsuit,jumpsuit"',
       '"Round neck,Plus Size,Necks,Summer,Dress,Loose,Pocket,Women\'s Fashion,Fashion,Pure Color,sleeveless,Casual,Women"'],
      dtype='<U368')

In [59]:
ventas = np.genfromtxt('datos/summer_products/ventas.csv', delimiter=',', dtype='float')

#62 filas, 8 columnas
ventas.shape

(62, 8)

In [60]:
# 'precio','precio al por menor', 'unidades vendidas', 'votos por 5 estrellas', 'votos por 4 estrellas', 'votos por 3 estrellas','votos por 2 estrellas', 'votos por 1 estrellas'
# Todos las columnas de los 5 primeros productos
ventas[:5,:]

array([[1.30e+01, 1.30e+01, 1.00e+03, 8.20e+01, 2.70e+01, 1.00e+01,
        7.00e+00, 1.20e+01],
       [9.00e+00, 8.00e+00, 5.00e+03, 4.00e+02, 1.42e+02, 1.03e+02,
        4.50e+01, 5.30e+01],
       [7.00e+00, 6.00e+00, 1.00e+02, 3.00e+01, 1.40e+01, 5.00e+00,
        1.00e+00, 3.00e+00],
       [1.10e+01, 1.00e+01, 5.00e+03, 4.47e+02, 2.01e+02, 1.35e+02,
        8.10e+01, 1.44e+02],
       [7.00e+00, 9.00e+00, 1.00e+03, 1.01e+02, 3.60e+01, 3.80e+01,
        1.50e+01, 2.90e+01]])

In [61]:
# precio de los 62 productos
ventas[:,0]

array([13.  ,  9.  ,  7.  , 11.  ,  7.  , 11.  , 19.  , 11.  , 11.  ,
        8.  , 13.  , 11.  ,  2.66,  3.67, 12.  ,  7.  ,  4.73, 11.  ,
       11.  ,  7.  ,  5.  , 11.  ,  7.  , 11.  ,  8.  ,  9.  ,  9.  ,
        5.74,  9.  , 11.  , 12.  ,  5.74, 12.  ,  7.  ,  3.  ,  6.  ,
        9.  ,  7.  ,  8.  ,  2.  , 11.  , 12.  ,  8.  ,  3.86,  1.86,
        9.  ,  7.  , 12.  ,  5.  , 12.  ,  7.  ,  5.  ,  7.  ,  5.65,
        8.  ,  8.  , 16.  ,  7.  , 16.  ,  6.  , 11.  , 13.  ])

In [62]:
# unidades vendidas de los 62 productos
ventas[:,2]

array([ 1000.,  5000.,   100.,  5000.,  1000.,   100.,  5000.,  1000.,
       20000.,   100.,   100., 20000.,   100.,  5000., 10000.,   100.,
         100., 20000.,   100.,   100.,  1000.,  1000.,  1000., 20000.,
       10000.,  1000.,  1000.,   100., 10000.,   100.,  1000., 10000.,
       20000.,  1000.,   100.,  5000.,   100.,  1000.,   100.,  1000.,
       20000.,  1000.,  1000.,   100.,  1000.,  1000.,  1000.,  1000.,
        5000.,  5000.,  1000.,  1000., 10000.,  1000.,   100.,  1000.,
        5000.,  1000., 10000., 10000., 20000., 10000.])

In [63]:
# Valores del primer producto
print(nombres[0])
print(ventas[0,:])

5 Color Women's Fashion Summer Slim Sleeveless Camouflage Print Dress High Waist Lace Up Casual Pocket Mini Dresses Plus Size S-5XL
[  13.   13. 1000.   82.   27.   10.    7.   12.]
